const otros = [
  {
    name: 'agro',
    title: 'INFRAESTRUCTURA AGROINDUSTRIAL',
    text: '<p>La tierra es uno de los activos más importantes de las comunidades rurales, suministra alimentos para sus familias y los eventuales excedentes pueden utilizarse para obtener ingresos adicionales. Para muchas comunidades que tienen una superficie de tierra insuficiente o nula para cubrir sus necesidades, su adquisición a través de un arrendamiento justo representa un gran avance para determinar su seguridad futura, pues viene a significar prácticamente su única solución, particularmente en aquellas regiones en las que los regímenes vigentes de tenencia de la tierra no les son favorables.</p><p>Para GEÔTICA INFRAESTRUCTURA AGROINDUSTRIAL es claro que permitiendo a la población rural un acceso seguro a las tierras de cultivo, vía el arrendamiento agrario, se cumple con una de las condiciones fundamentales para reducir la marginación, la pobreza y el hambre en nuestras comunidades, pues se promueve así un desarrollo realmente sostenible en sus personas al mejorarles sus medios de subsistencia.</p><p>Como grupo empresarial alineado totalmente a las directrices establecidas por la FAO (Organización de las Naciones Unidas para la Alimentación y la Agricultura), queremos responder a la preocupación generalizada de seguridad alimentaria y mitigación de la pobreza en sus Países miembros, por lo que hemos decidido sujetar el modelo de negocios de nuestros proyectos agroindustriales, desde sus etapas más tempranas, a estos mecanismos de arrendamiento equitativo y seguro, por considerarlos recíprocamente beneficiosos, pues compaginan cabalmente los intereses del arrendatario y los de nuestro grupo, a fin de que ambas partes, juntas, podamos favorecer el acceso a la tierra agrícola, mejorando su explotación y producción, facilitando y asegurando el acceso a los alimentos y, no menos importante, evitando las lamentables situaciones de desigualdad social.</p><p>Por todo lo anterior, GEÓTICA INFRAESTRUCTURA AGROINDUSTRIAL considera que el éxito de este tipo de arrendamientos, mutuamente beneficiosos, depende del nivel de confianza que se pueda establecer entre las partes; sabemos que un acuerdo bien concebido puede servir de base para conseguir esta confianza y aminorar los riesgos mutuos, haciendo posible lograr tanto la flexibilidad requerida en nuestros proyectos como la anhelada seguridad para el arrendatario durante el período del contrato.</p><p>Con este tipo de perspectivas empresariales, nos convencemos aún más de ir por el camino correcto:</p><p class="resaltar">Desarrollar soluciones creativas que mejoren la vida de las comunidades.</p>',
  },
  {
    name: 'educativa',
    title: 'INFRAESTRUCTURA EDUCATIVA, DEPORTIVA Y CULTURAL',
    text: '<p>El compromiso social que GEÔTICA asume con el bienestar de las comunidades en que servimos, forma parte de nuestro sentido de responsabilidad, firmemente alineado con los valores corporativos del Grupo.</p><p>Desde hace algunos años iniciamos nuestro compromiso con la sociedad, coadyuvando en una primera etapa en 78 proyectos con el Instituto Nacional de la Infraestructura Física Educativa, Capítulo Jalisco, en la ampliación y mejoramiento de la infraestructura educativa de 27 Municipios del Estado, sensibilizándonos en todos esos años de las muchas necesidades que aún prevalecen en nuestras comunidades y concientizándonos también de lo mucho que podemos aportar desde nuestras áreas de especialización.</p><p>Sin ser precisamente los sectores educativo, deportivo o cultural áreas de nuestra competencia ingenieril, no hemos podido ser indiferentes a la gran cantidad de necesidades que palpamos en nuestras diarias actuaciones a lo largo y ancho del país, por lo que hemos venido identificando lo mucho que podemos aportar para incidir de forma positiva en cada lugar en que trabajamos.</p><p>Hoy más que nunca encontramos sentido en nuestra razón de ser y estamos convencidos de que vamos en el rumbo correcto:</p><p class="resaltar">Desarrollar soluciones creativas que mejoren la vida de las comunidades.</p>',
  },
];

export default otros;
